#pragma once

#define ENCODER_RESOLUTION 4
#define KC_CAD C(A(KC_DEL))
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 6 
#define MOUSEKEY_WHEEL_DELAY 0